
const STATE = {
  lang: localStorage.getItem('site_lang') || 'ar',
  enrolled: JSON.parse(localStorage.getItem('enrolled')||'[]')
};
const TRANSLATIONS = {
  en: { home:'Home', courses:'Courses', books:'Books', library:'Library', categories:'Categories', dashboard:'Dashboard', about:'About', contact:'Contact', search_placeholder:'Search courses, topics, or instructors...', enroll:'Enroll', view:'View', no_enroll:'Not enrolled yet', my_courses:'My Courses', certificates:'Certificates' },
  ar: { home:'الرئيسية', courses:'الدورات', books:'الكتب', library:'المكتبة', categories:'التصنيفات', dashboard:'لوحة الطالب', about:'من نحن', contact:'اتصل بنا', search_placeholder:'ابحث عن دورة، تقنية أو مدرس...', enroll:'الالتحاق', view:'عرض', no_enroll:'لم تلتحق بأي دورة بعد', my_courses:'دوراتك', certificates:'الشهادات' }
};
const DATA = {
  courses: [
    {id:'c1',title_ar:'إتقان جافاسكربت', title_en:'Mastering JavaScript', teacher:'Ali Hassan', rating:4.7, price:'Free', img:'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80', desc_ar:'دورة شاملة عن جافاسكربت', desc_en:'Comprehensive JS course'},
    {id:'c2',title_ar:'بايثون لعلوم البيانات', title_en:'Python for Data Science', teacher:'Sara Ibrahim', rating:4.8, price:'$19.99', img:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80', desc_ar:'مشاريع عملية بالبايثون', desc_en:'Hands-on Python projects'},
    {id:'c3',title_ar:'أساسيات تصميم UX', title_en:'UI/UX Design Fundamentals', teacher:'Lina Khaled', rating:4.6, price:'$14.99', img:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80', desc_ar:'تصميم واجهات مستخدم', desc_en:'Design interfaces'},
    {id:'c4',title_ar:'React من الصفر', title_en:'React - The Complete Guide', teacher:'Omar Saeed', rating:4.9, price:'$24.99', img:'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80', desc_ar:'تعلم React عمليًا', desc_en:'From hooks to optimization'},
    {id:'c5',title_ar:'تعلم AWS', title_en:'AWS Cloud Practitioner', teacher:'Ahmed Zaki', rating:4.3, price:'$17.99', img:'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80', desc_ar:'مقدمة لخدمات AWS', desc_en:'Intro to AWS cloud services'}
  ],
  books: [
    {id:'b1',title_en:'Eloquent JavaScript', title_ar:'Eloquent JavaScript', author:'Marijn Haverbeke', source:'https://eloquentjavascript.net/'},
    {id:'b2',title_en:"You Don't Know JS", title_ar:"You Don't Know JS", author:'Kyle Simpson', source:'https://github.com/getify/You-Dont-Know-JS'},
    {id:'b3',title_en:'Think Python', title_ar:'Think Python', author:'Allen B. Downey', source:'https://greenteapress.com/thinkpython/'}
  ]
};
function t(k){ return TRANSLATIONS[STATE.lang][k] || k; }
function formatCourse(c){ return STATE.lang==='ar' ? c.title_ar : c.title_en; }
function formatDesc(c){ return STATE.lang==='ar' ? c.desc_ar : c.desc_en; }
function renderHeaderElements(){ document.querySelectorAll('.lang-btn').forEach(b=> b.classList.toggle('active', b.dataset.lang===STATE.lang)); const search = document.querySelectorAll('.search-input'); search.forEach(s=> s.placeholder = t('search_placeholder')); }
function setActiveNav(){ const p = window.location.pathname.split('/').pop() || 'index.html'; document.querySelectorAll('.nav a').forEach(a=>{ const href = a.getAttribute('href') || ''; a.classList.toggle('active', href===p); }); }
function renderCoursesGrid(selector, listData){ const wrap = document.querySelector(selector); if(!wrap) return; wrap.innerHTML = ''; const list = listData || DATA.courses; list.forEach(c=>{ const div = document.createElement('div'); div.className='card'; div.innerHTML = "<div class='thumb' style=\"background-image:url('"+c.img+"')\"></div><div class='card-body'><div class='title'>"+formatCourse(c)+"</div><div class='meta'>"+c.teacher+" • ⭐ "+c.rating+"</div><div class='foot'><div class='price'>"+c.price+"</div><div><a class='btn' href='course.html?id="+c.id+"'>"+ t('view') +"</a></div></div></div>"; wrap.appendChild(div); }); const total = document.getElementById('total-courses'); if(total) total.textContent = DATA.courses.length + ' دورات'; }
function renderBooksGrid(selector){ const wrap = document.querySelector(selector); if(!wrap) return; wrap.innerHTML = ''; DATA.books.forEach(b=>{ const div = document.createElement('div'); div.className='card'; div.innerHTML = "<div class='card-body'><div class='title'>"+ (STATE.lang==='ar'?b.title_ar:b.title_en) +"</div><div class='meta'>المؤلف: "+b.author+"</div><div style='margin-top:auto'><a class='btn' href='"+b.source+"' target='_blank'>"+ (STATE.lang==='ar'?'المصدر':'Source') +"</a></div></div>"; wrap.appendChild(div); }); }
function renderCourseDetail(){ const q = new URL(location.href).searchParams; const id = q.get('id'); if(!id) return; const c = DATA.courses.find(x=>x.id===id); if(!c) return; const area = document.getElementById('course-area'); if(!area) return; area.innerHTML = "<div class='detail'><div><div class='card'><div class='thumb' style=\"background-image:url('"+c.img+"');height:320px\"></div><div class='card-body'><h2 class='title'>"+ formatCourse(c) +"</h2><div class='meta'>"+c.teacher+" • ⭐ "+c.rating+"</div><p style='margin-top:12px'>"+ formatDesc(c) +"</p></div></div></div><aside><div class='card card-body'><div style='font-weight:800'>"+ t('enroll') +"</div><div style='margin-top:12px'><button id='enroll-btn' class='btn'>"+ t('enroll') +"</button></div></div></aside></div><div style='margin-top:12px'><h3>الدروس</h3><div id='lessons'></div></div>"; const lessonsWrap = document.getElementById('lessons'); for(let i=1;i<=8;i++){ const l = document.createElement('div'); l.className='lesson'; l.innerHTML = "<div>"+ (STATE.lang==='ar'?'درس '+i:'Lesson '+i) +"</div><div><button class='ghost mark' data-id='"+id+"_l"+i+"'>✓</button></div>"; lessonsWrap.appendChild(l); } document.getElementById('enroll-btn').addEventListener('click', ()=>{ if(!STATE.enrolled.includes(id)){ STATE.enrolled.push(id); localStorage.setItem('enrolled', JSON.stringify(STATE.enrolled)); alert(STATE.lang==='ar'?'تم الالتحاق (تجريبي)':'Enrolled (demo)'); renderDashboard(); } else alert(STATE.lang==='ar'?'أنت ملتحق بالفعل':'Already enrolled'); }); document.addEventListener('click', e=>{ if(e.target.matches('.mark')){ const key = 'progress_'+e.target.dataset.id.split('_')[0]; const prog = JSON.parse(localStorage.getItem(key)||'{"completed":[]}'); if(!prog.completed.includes(e.target.dataset.id)){ prog.completed.push(e.target.dataset.id); localStorage.setItem(key, JSON.stringify(prog)); e.target.textContent='✔'; checkIssueCert(e.target.dataset.id.split('_')[0]); } } }); }
function checkIssueCert(courseId){ const key = 'progress_'+courseId; const prog = JSON.parse(localStorage.getItem(key)||'{"completed":[]}'); if(prog.completed.length>=8){ const certs = JSON.parse(localStorage.getItem('certs')||'{}'); if(!certs[courseId]){ certs[courseId] = {id: courseId+'-'+Date.now(), name: (STATE.lang==='ar'? (DATA.courses.find(c=>c.id===courseId).title_ar) : DATA.courses.find(c=>c.id===courseId).title_en), issuedAt: Date.now() }; localStorage.setItem('certs', JSON.stringify(certs)); alert(STATE.lang==='ar'?'تم إصدار شهادة للدورة!':'Certificate issued!'); renderDashboard(); } } }
function renderDashboard(){ const wrap = document.getElementById('my-courses'); if(!wrap) return; wrap.innerHTML = ''; const enrolled = JSON.parse(localStorage.getItem('enrolled')||'[]'); if(enrolled.length===0){ wrap.innerHTML = "<div class='card'><div class='card-body'><div class='meta'>"+ t('no_enroll') +"</div></div></div>"; return; } enrolled.forEach(id=>{ const c = DATA.courses.find(x=>x.id===id); if(!c) return; const d = document.createElement('div'); d.className='card'; d.style.marginBottom='10px'; d.innerHTML = "<div class='card-body' style='display:flex;gap:12px;align-items:center'><img src='"+c.img+"' style='width:160px;height:90px;object-fit:cover;border-radius:8px'/><div style='flex:1'><div class='title'>"+ (STATE.lang==='ar'?c.title_ar:c.title_en) +"</div><div class='meta'>"+c.teacher+"</div><div style='margin-top:8px'><a class='btn' href='course.html?id="+c.id+"'>"+ t('view') +"</a></div></div></div>"; wrap.appendChild(d); }); const certWrap = document.getElementById('certs'); if(certWrap){ certWrap.innerHTML=''; const certs = JSON.parse(localStorage.getItem('certs')||'{}'); const keys = Object.keys(certs); if(keys.length===0){ certWrap.innerHTML = "<div class='meta'>لا توجد شهادات بعد.</div>"; } else { keys.forEach(k=>{ const obj = certs[k]; const el = document.createElement('div'); el.className='card'; el.style.marginBottom='8px'; el.innerHTML = "<div class='card-body'><div style='font-weight:700'>"+obj.name+"</div><div class='meta'>ID: "+obj.id+" — "+ (new Date(obj.issuedAt)).toLocaleString() +"</div></div>"; certWrap.appendChild(el); }); } } }
function initSite(){ document.querySelectorAll('.lang-btn').forEach(b=> b.addEventListener('click', ()=>{ STATE.lang = b.dataset.lang; localStorage.setItem('site_lang', STATE.lang); applyLangUI(); })); applyLangUI(); setActiveNav(); renderCoursesGrid('#courses-grid'); renderBooksGrid('#books-grid'); renderCourseDetail(); renderDashboard(); renderHeaderElements(); const s = document.querySelectorAll('.search-input'); s.forEach(inp=> inp.addEventListener('input',(e)=>{ const q = e.target.value.toLowerCase(); const filtered = DATA.courses.filter(c=> (c.title_en+c.title_ar+c.teacher+c.desc_en+c.desc_ar).toLowerCase().includes(q)); renderCoursesGrid('#courses-grid', filtered); })); }
function applyLangUI(){ renderHeaderElements(); document.querySelectorAll('[data-i18n-key]').forEach(el=>{ const k = el.dataset.i18nKey; el.textContent = TRANSLATIONS[STATE.lang][k]; }); renderCoursesGrid('#courses-grid'); renderBooksGrid('#books-grid'); renderDashboard(); }
document.addEventListener('DOMContentLoaded', initSite);
